### ISSUE TITLE
How to define which device is receiving the notification

### ISSUE THREAD

**Issue by MTrab** [MCrissDev/HANotify#8]
Where do you define which device the notify.android is?

Right now none of my devices are receiving any notifications.

**Comment by MCrissDev** [comment]
Hello,
notify.android if used means that all devices should receive the notifications.
When a device is registered from Ariela, it will automatically create a notify item. For example in my case, "notify.android_ionut" is created and i can use that to send notifications only to my phone. Please let me know if works.

**Comment by MTrab** [comment]
Unfortunately this is not the case with me :(

Do I need to do anything other than activate notifications on the phone? (I have the .py file in HA and have setup the platform)

This is the only notify items I have
![Notify](https://user-images.githubusercontent.com/14296463/56789422-1d299b00-6802-11e9-9033-a86a3bfe892b.PNG)

**Comment by MCrissDev** [comment]
Make sure the device name is set in Ariela (Settings -> Common).
After that go to Settings -> Notifications and enable firebase notifications. Please check if a success toast appear. If that toast do not appear, please send me Ariela logs.

**Comment by MTrab** [comment]
`Firebase notifications has been enabled` is what it says when enabling - but nothing happens in HA.
Device tracker function is working and name is set.

**Comment by MCrissDev** [comment]
What happens if you do a restart of the HA server? Does the notify devices appear?

**Comment by MTrab** [comment]
For some reason it started working after upgrade from HA .91 to .92.
